import { defineStore } from 'pinia'

export const useSearchStore = defineStore('search', {
  state: () => ({
    accommodations: [
      {
        borough: 'La D\u00e9fense',
        category: 'Alcove',
        bedrooms: 4,
        city: 'Paris',
        country: 'France',
        id: 1,
        image: 'https://images.unsplash.com/photo-1595526110121-b6b5f62e4875',
        price: 1595,
        rating: 5,
        reviews: 26,
        title: 'Apartment in Canal Saint-Martin with unique charm',
      },
      {
        borough: 'M\u00e9nilmontant',
        category: 'Studio',
        bedrooms: 1,
        city: 'Paris',
        country: 'France',
        id: 2,
        image: 'https://images.unsplash.com/photo-1596424529403-448a0dba59cf',
        price: 1651,
        rating: 5,
        reviews: 14,
        title: 'Apartment in P\u00e8re Lachaise with unique charm',
      },
      {
        borough: 'Opera',
        category: 'Apartment',
        bedrooms: 1,
        city: 'Paris',
        country: 'France',
        id: 3,
        image: 'https://images.unsplash.com/photo-1596424529403-448a0dba59cf',
        price: 1788,
        rating: 5,
        reviews: 15,
        title: 'Apartment in M\u00e9nilmontant with unique charm',
      },
      {
        borough: 'Trocad\u00e9ro',
        category: 'Apartment',
        bedrooms: 2,
        city: 'Paris',
        country: 'France',
        id: 4,
        image: 'https://images.unsplash.com/photo-1596424529403-448a0dba59cf',
        price: 2695,
        rating: 5,
        reviews: 22,
        title: 'Apartment in Saint-Germain-des-Pr\u00e9s with unique charm',
      },
      {
        borough: 'Gobelins',
        category: 'Apartment',
        bedrooms: 2,
        city: 'Paris',
        country: 'France',
        id: 5,
        image: 'https://images.unsplash.com/photo-1565182999561-9c5ed6813233',
        price: 3983,
        rating: 4,
        reviews: 23,
        title: 'Apartment in Le Marais with unique charm',
      },
      {
        borough: 'Gobelins',
        category: 'Studio',
        bedrooms: 2,
        city: 'Paris',
        country: 'France',
        id: 6,
        image: 'https://images.unsplash.com/photo-1595152772835-219674b2a8a6',
        price: 3047,
        rating: 3,
        reviews: 21,
        title: 'Apartment in Saint-Germain-des-Pr\u00e9s with unique charm',
      },
      {
        borough: 'M\u00e9nilmontant',
        category: 'Apartment',
        bedrooms: 2,
        city: 'Paris',
        country: 'France',
        id: 7,
        image: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae',
        price: 3218,
        rating: 5,
        reviews: 20,
        title: 'Apartment in Butte-aux-Cailles with unique charm',
      },
      {
        borough: 'Gobelins',
        category: 'Apartment',
        bedrooms: 2,
        city: 'Paris',
        country: 'France',
        id: 8,
        image: 'https://images.unsplash.com/photo-1557683326-6e496f8fac2b',
        price: 4233,
        rating: 3,
        reviews: 30,
        title: 'Apartment in Batignolles with unique charm',
      },
      {
        borough: 'Le Marais',
        category: 'Apartment',
        bedrooms: 2,
        city: 'Paris',
        country: 'France',
        id: 9,
        image: 'https://images.unsplash.com/photo-1560448204-e2b83c486b95',
        price: 4393,
        rating: 4,
        reviews: 16,
        title: 'Apartment in Opera with unique charm',
      },
      {
        borough: 'Canal Saint-Martin',
        category: 'Apartment',
        bedrooms: 2,
        city: 'Paris',
        country: 'France',
        id: 10,
        image: 'https://images.unsplash.com/photo-1576675788763-d296b2892211',
        price: 1564,
        rating: 4,
        reviews: 23,
        title: 'Apartment in Canal Saint-Martin with unique charm',
      },
      {
        borough: 'Opera',
        category: 'Apartment',
        bedrooms: 1,
        city: 'Paris',
        country: 'France',
        id: 11,
        image: 'https://images.unsplash.com/photo-1557683326-6e496f8fac2b',
        price: 4445,
        rating: 3,
        reviews: 18,
        title: 'Apartment in P\u00e8re Lachaise with unique charm',
      },
      {
        borough: 'Les Halles',
        category: 'Alcove',
        bedrooms: 1,
        city: 'Paris',
        country: 'France',
        id: 12,
        image: 'https://images.unsplash.com/photo-1565182999561-9c5ed6813233',
        price: 1972,
        rating: 3,
        reviews: 28,
        title: 'Apartment in La D\u00e9fense with unique charm',
      },
      {
        borough: 'Opera',
        category: 'Studio',
        bedrooms: 2,
        city: 'Paris',
        country: 'France',
        id: 13,
        image: 'https://images.unsplash.com/photo-1595152772835-219674b2a8a6',
        price: 3762,
        rating: 4,
        reviews: 7,
        title: 'Apartment in Belleville with unique charm',
      },
      {
        borough: 'Butte-aux-Cailles',
        category: 'Apartment',
        bedrooms: 4,
        city: 'Paris',
        country: 'France',
        id: 14,
        image: 'https://images.unsplash.com/photo-1557683326-6e496f8fac2b',
        price: 1206,
        rating: 5,
        reviews: 23,
        title: 'Apartment in Bastille with unique charm',
      },
      {
        borough: 'Latin Quarter',
        category: 'Apartment',
        bedrooms: 3,
        city: 'Paris',
        country: 'France',
        id: 15,
        image: 'https://images.unsplash.com/photo-1576675788763-d296b2892211',
        price: 3148,
        rating: 4,
        reviews: 13,
        title: 'Apartment in Butte-aux-Cailles with unique charm',
      },
      {
        borough: 'Latin Quarter',
        category: 'Apartment',
        bedrooms: 4,
        city: 'Paris',
        country: 'France',
        id: 16,
        image: 'https://images.unsplash.com/photo-1605276375032-69b768b550cc',
        price: 3326,
        rating: 3,
        reviews: 26,
        title: 'Apartment in Pigalle with unique charm',
      },
      {
        borough: 'M\u00e9nilmontant',
        category: 'Apartment',
        bedrooms: 4,
        city: 'Paris',
        country: 'France',
        id: 17,
        image: 'https://images.unsplash.com/photo-1605276375032-69b768b550cc',
        price: 2627,
        rating: 4,
        reviews: 17,
        title: 'Apartment in Pigalle with unique charm',
      },
      {
        borough: 'Trocad\u00e9ro',
        category: 'Apartment',
        bedrooms: 2,
        city: 'Paris',
        country: 'France',
        id: 18,
        image: 'https://images.unsplash.com/photo-1576675788763-d296b2892211',
        price: 4835,
        rating: 5,
        reviews: 29,
        title: 'Apartment in Opera with unique charm',
      },
      {
        borough: 'Le Marais',
        category: 'Alcove',
        bedrooms: 1,
        city: 'Paris',
        country: 'France',
        id: 19,
        image: 'https://images.unsplash.com/photo-1576675788763-d296b2892211',
        price: 1627,
        rating: 4,
        reviews: 29,
        title: 'Apartment in Les Halles with unique charm',
      },
      {
        borough: 'Batignolles',
        category: 'Apartment',
        bedrooms: 1,
        city: 'Paris',
        country: 'France',
        id: 20,
        image: 'https://images.unsplash.com/photo-1605276375032-69b768b550cc',
        price: 3069,
        rating: 4,
        reviews: 25,
        title: 'Apartment in M\u00e9nilmontant with unique charm',
      },
      {
        borough: 'Gobelins',
        category: 'Apartment',
        bedrooms: 4,
        city: 'Paris',
        country: 'France',
        id: 21,
        image: 'https://images.unsplash.com/photo-1557683326-6e496f8fac2b',
        price: 3642,
        rating: 3,
        reviews: 23,
        title: 'Apartment in Trocad\u00e9ro with unique charm',
      },
      {
        borough: 'Bastille',
        category: 'Apartment',
        bedrooms: 3,
        city: 'Paris',
        country: 'France',
        id: 22,
        image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
        price: 4528,
        rating: 5,
        reviews: 13,
        title: "Apartment in Place d'Italie with unique charm",
      },
      {
        borough: 'La D\u00e9fense',
        category: 'Studio',
        bedrooms: 1,
        city: 'Paris',
        country: 'France',
        id: 23,
        image: 'https://images.unsplash.com/photo-1560448204-e2b83c486b95',
        price: 1697,
        rating: 4,
        reviews: 10,
        title: 'Apartment in Pigalle with unique charm',
      },
      {
        borough: 'Auteuil',
        category: 'Apartment',
        bedrooms: 3,
        city: 'Paris',
        country: 'France',
        id: 24,
        image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
        price: 3904,
        rating: 3,
        reviews: 11,
        title: 'Apartment in Belleville with unique charm',
      },
      {
        borough: 'Les Halles',
        category: 'Studio',
        bedrooms: 1,
        city: 'Paris',
        country: 'France',
        id: 25,
        image: 'https://images.unsplash.com/photo-1557683326-6e496f8fac2b',
        price: 1994,
        rating: 4,
        reviews: 28,
        title: 'Apartment in Les Halles with unique charm',
      },
      {
        borough: 'M\u00e9nilmontant',
        category: 'Apartment',
        bedrooms: 1,
        city: 'Paris',
        country: 'France',
        id: 26,
        image: 'https://images.unsplash.com/photo-1576675788763-d296b2892211',
        price: 2813,
        rating: 3,
        reviews: 16,
        title: 'Apartment in Auteuil with unique charm',
      },
      {
        borough: 'Canal Saint-Martin',
        category: 'Apartment',
        bedrooms: 1,
        city: 'Paris',
        country: 'France',
        id: 27,
        image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
        price: 1981,
        rating: 3,
        reviews: 21,
        title: 'Apartment in Gobelins with unique charm',
      },
      {
        borough: 'Opera',
        category: 'Apartment',
        bedrooms: 3,
        city: 'Paris',
        country: 'France',
        id: 28,
        image: 'https://images.unsplash.com/photo-1596424529403-448a0dba59cf',
        price: 4511,
        rating: 3,
        reviews: 29,
        title: 'Apartment in Champs-\u00c9lys\u00e9es with unique charm',
      },
      {
        borough: 'Montmartre',
        category: 'Apartment',
        bedrooms: 3,
        city: 'Paris',
        country: 'France',
        id: 29,
        image: 'https://images.unsplash.com/photo-1557683326-6e496f8fac2b',
        price: 1841,
        rating: 3,
        reviews: 14,
        title: 'Apartment in Opera with unique charm',
      },
      {
        borough: 'Champs-\u00c9lys\u00e9es',
        category: 'Apartment',
        bedrooms: 2,
        city: 'Paris',
        country: 'France',
        id: 30,
        image: 'https://images.unsplash.com/photo-1557683326-6e496f8fac2b',
        price: 3019,
        rating: 4,
        reviews: 19,
        title: 'Apartment in Canal Saint-Martin with unique charm',
      },
      {
        borough: 'Batignolles',
        category: 'Apartment',
        bedrooms: 3,
        city: 'Paris',
        country: 'France',
        id: 31,
        image: 'https://images.unsplash.com/photo-1596424529403-448a0dba59cf',
        price: 4274,
        rating: 4,
        reviews: 25,
        title: 'Apartment in Pigalle with unique charm',
      },
      {
        borough: "Place d'Italie",
        category: 'Alcove',
        bedrooms: 4,
        city: 'Paris',
        country: 'France',
        id: 32,
        image: 'https://images.unsplash.com/photo-1596424529403-448a0dba59cf',
        price: 3710,
        rating: 4,
        reviews: 17,
        title: 'Apartment in Saint-Germain-des-Pr\u00e9s with unique charm',
      },
      {
        borough: 'Canal Saint-Martin',
        category: 'Apartment',
        bedrooms: 1,
        city: 'Paris',
        country: 'France',
        id: 33,
        image: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae',
        price: 2430,
        rating: 5,
        reviews: 30,
        title: "Apartment in Place d'Italie with unique charm",
      },
      {
        borough: 'Les Halles',
        category: 'Apartment',
        bedrooms: 4,
        city: 'Paris',
        country: 'France',
        id: 34,
        image: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae',
        price: 3132,
        rating: 4,
        reviews: 7,
        title: 'Apartment in Latin Quarter with unique charm',
      },
      {
        borough: 'Batignolles',
        category: 'Apartment',
        bedrooms: 4,
        city: 'Paris',
        country: 'France',
        id: 35,
        image: 'https://images.unsplash.com/photo-1596424529403-448a0dba59cf',
        price: 4016,
        rating: 5,
        reviews: 16,
        title: 'Apartment in Opera with unique charm',
      },
      {
        borough: 'Butte-aux-Cailles',
        category: 'Apartment',
        bedrooms: 2,
        city: 'Paris',
        country: 'France',
        id: 36,
        image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
        price: 3942,
        rating: 5,
        reviews: 7,
        title: 'Apartment in P\u00e8re Lachaise with unique charm',
      },
      {
        borough: 'Batignolles',
        category: 'Apartment',
        bedrooms: 3,
        city: 'Paris',
        country: 'France',
        id: 37,
        image: 'https://images.unsplash.com/photo-1595152772835-219674b2a8a6',
        price: 1894,
        rating: 3,
        reviews: 10,
        title: 'Apartment in Belleville with unique charm',
      },
      {
        borough: 'Pigalle',
        category: 'Studio',
        bedrooms: 2,
        city: 'Paris',
        country: 'France',
        id: 38,
        image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
        price: 1403,
        rating: 4,
        reviews: 23,
        title: "Apartment in Place d'Italie with unique charm",
      },
      {
        borough: 'Gobelins',
        category: 'Apartment',
        bedrooms: 1,
        city: 'Paris',
        country: 'France',
        id: 39,
        image: 'https://images.unsplash.com/photo-1565182999561-9c5ed6813233',
        price: 2707,
        rating: 5,
        reviews: 24,
        title: 'Apartment in Butte-aux-Cailles with unique charm',
      },
      {
        borough: 'Belleville',
        category: 'Apartment',
        bedrooms: 3,
        city: 'Paris',
        country: 'France',
        id: 40,
        image: 'https://images.unsplash.com/photo-1596424529403-448a0dba59cf',
        price: 4271,
        rating: 3,
        reviews: 25,
        title: 'Apartment in Le Marais with unique charm',
      },
      {
        borough: 'Le Marais',
        category: 'Apartment',
        bedrooms: 1,
        city: 'Paris',
        country: 'France',
        id: 41,
        image: 'https://images.unsplash.com/photo-1605276375032-69b768b550cc',
        price: 2355,
        rating: 3,
        reviews: 26,
        title: 'Apartment in Latin Quarter with unique charm',
      },
      {
        borough: 'Les Halles',
        category: 'Apartment',
        bedrooms: 2,
        city: 'Paris',
        country: 'France',
        id: 42,
        image: 'https://images.unsplash.com/photo-1595526110121-b6b5f62e4875',
        price: 2787,
        rating: 5,
        reviews: 30,
        title: 'Apartment in Latin Quarter with unique charm',
      },
      {
        borough: 'Les Halles',
        category: 'Alcove',
        bedrooms: 1,
        city: 'Paris',
        country: 'France',
        id: 43,
        image: 'https://images.unsplash.com/photo-1595526110121-b6b5f62e4875',
        price: 4304,
        rating: 4,
        reviews: 20,
        title: 'Apartment in Trocad\u00e9ro with unique charm',
      },
      {
        borough: 'Champs-\u00c9lys\u00e9es',
        category: 'Apartment',
        bedrooms: 4,
        city: 'Paris',
        country: 'France',
        id: 44,
        image: 'https://images.unsplash.com/photo-1595526110121-b6b5f62e4875',
        price: 2695,
        rating: 5,
        reviews: 13,
        title: 'Apartment in Gobelins with unique charm',
      },
      {
        borough: 'Gobelins',
        category: 'Apartment',
        bedrooms: 2,
        city: 'Paris',
        country: 'France',
        id: 45,
        image: 'https://images.unsplash.com/photo-1605276375032-69b768b550cc',
        price: 3353,
        rating: 3,
        reviews: 17,
        title: 'Apartment in P\u00e8re Lachaise with unique charm',
      },
      {
        borough: 'La D\u00e9fense',
        category: 'Apartment',
        bedrooms: 2,
        city: 'Paris',
        country: 'France',
        id: 46,
        image: 'https://images.unsplash.com/photo-1595526110121-b6b5f62e4875',
        price: 3191,
        rating: 4,
        reviews: 9,
        title: 'Apartment in Trocad\u00e9ro with unique charm',
      },
      {
        borough: 'La D\u00e9fense',
        category: 'Apartment',
        bedrooms: 1,
        city: 'Paris',
        country: 'France',
        id: 47,
        image: 'https://images.unsplash.com/photo-1576675788763-d296b2892211',
        price: 1361,
        rating: 3,
        reviews: 15,
        title: 'Apartment in Le Marais with unique charm',
      },
      {
        borough: 'La D\u00e9fense',
        category: 'Studio',
        bedrooms: 4,
        city: 'Paris',
        country: 'France',
        id: 48,
        image: 'https://images.unsplash.com/photo-1605276375032-69b768b550cc',
        price: 1379,
        rating: 5,
        reviews: 18,
        title: 'Apartment in Bastille with unique charm',
      },
      {
        borough: 'Gobelins',
        category: 'Apartment',
        bedrooms: 4,
        city: 'Paris',
        country: 'France',
        id: 49,
        image: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae',
        price: 1908,
        rating: 4,
        reviews: 20,
        title: 'Apartment in Butte-aux-Cailles with unique charm',
      },
      {
        borough: 'Latin Quarter',
        category: 'Apartment',
        bedrooms: 2,
        city: 'Paris',
        country: 'France',
        id: 50,
        image: 'https://images.unsplash.com/photo-1576675788763-d296b2892211',
        price: 4091,
        rating: 5,
        reviews: 20,
        title: 'Apartment in Auteuil with unique charm',
      },
      {
        borough: 'Latin Quarter',
        category: 'Apartment',
        bedrooms: 4,
        city: 'Paris',
        country: 'France',
        id: 51,
        image: 'https://images.unsplash.com/photo-1595152772835-219674b2a8a6',
        price: 1566,
        rating: 3,
        reviews: 18,
        title: 'Apartment in Belleville with unique charm',
      },
      {
        borough: 'Montmartre',
        category: 'Apartment',
        bedrooms: 1,
        city: 'Paris',
        country: 'France',
        id: 52,
        image: 'https://images.unsplash.com/photo-1605276375032-69b768b550cc',
        price: 2401,
        rating: 4,
        reviews: 15,
        title: "Apartment in Place d'Italie with unique charm",
      },
      {
        borough: 'Belleville',
        category: 'Alcove',
        bedrooms: 1,
        city: 'Paris',
        country: 'France',
        id: 53,
        image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
        price: 3325,
        rating: 5,
        reviews: 26,
        title: 'Apartment in Saint-Germain-des-Pr\u00e9s with unique charm',
      },
      {
        borough: 'Pigalle',
        category: 'Apartment',
        bedrooms: 2,
        city: 'Paris',
        country: 'France',
        id: 54,
        image: 'https://images.unsplash.com/photo-1565182999561-9c5ed6813233',
        price: 1345,
        rating: 5,
        reviews: 13,
        title: 'Apartment in Opera with unique charm',
      },
      {
        borough: 'La D\u00e9fense',
        category: 'Apartment',
        bedrooms: 3,
        city: 'Paris',
        country: 'France',
        id: 55,
        image: 'https://images.unsplash.com/photo-1595526110121-b6b5f62e4875',
        price: 2445,
        rating: 3,
        reviews: 16,
        title: 'Apartment in Le Marais with unique charm',
      },
      {
        borough: 'M\u00e9nilmontant',
        category: 'Apartment',
        bedrooms: 2,
        city: 'Paris',
        country: 'France',
        id: 56,
        image: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae',
        price: 3880,
        rating: 3,
        reviews: 6,
        title: 'Apartment in Opera with unique charm',
      },
      {
        borough: 'Montmartre',
        category: 'Apartment',
        bedrooms: 3,
        city: 'Paris',
        country: 'France',
        id: 57,
        image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
        price: 2976,
        rating: 4,
        reviews: 16,
        title: 'Apartment in Les Halles with unique charm',
      },
      {
        borough: 'Saint-Germain-des-Pr\u00e9s',
        category: 'Apartment',
        bedrooms: 4,
        city: 'Paris',
        country: 'France',
        id: 58,
        image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
        price: 3052,
        rating: 4,
        reviews: 15,
        title: 'Apartment in P\u00e8re Lachaise with unique charm',
      },
      {
        borough: 'Saint-Germain-des-Pr\u00e9s',
        category: 'Apartment',
        bedrooms: 2,
        city: 'Paris',
        country: 'France',
        id: 59,
        image: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae',
        price: 2281,
        rating: 4,
        reviews: 19,
        title: 'Apartment in Bastille with unique charm',
      },
      {
        borough: 'Belleville',
        category: 'Apartment',
        bedrooms: 4,
        city: 'Paris',
        country: 'France',
        id: 60,
        image: 'https://images.unsplash.com/photo-1596424529403-448a0dba59cf',
        price: 3706,
        rating: 5,
        reviews: 9,
        title: 'Apartment in Champs-\u00c9lys\u00e9es with unique charm',
      },
      {
        borough: 'Les Halles',
        category: 'Studio',
        bedrooms: 1,
        city: 'Paris',
        country: 'France',
        id: 61,
        image: 'https://images.unsplash.com/photo-1557683326-6e496f8fac2b',
        price: 4101,
        rating: 5,
        reviews: 20,
        title: 'Apartment in Trocad\u00e9ro with unique charm',
      },
      {
        borough: 'Butte-aux-Cailles',
        category: 'Apartment',
        bedrooms: 1,
        city: 'Paris',
        country: 'France',
        id: 62,
        image: 'https://images.unsplash.com/photo-1565182999561-9c5ed6813233',
        price: 2852,
        rating: 5,
        reviews: 19,
        title: 'Apartment in Les Halles with unique charm',
      },
      {
        borough: 'Canal Saint-Martin',
        category: 'Apartment',
        bedrooms: 2,
        city: 'Paris',
        country: 'France',
        id: 63,
        image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
        price: 1551,
        rating: 3,
        reviews: 22,
        title: 'Apartment in Champs-\u00c9lys\u00e9es with unique charm',
      },
      {
        borough: 'Trocad\u00e9ro',
        category: 'Apartment',
        bedrooms: 4,
        city: 'Paris',
        country: 'France',
        id: 64,
        image: 'https://images.unsplash.com/photo-1595152772835-219674b2a8a6',
        price: 3648,
        rating: 5,
        reviews: 11,
        title: 'Apartment in Butte-aux-Cailles with unique charm',
      },
      {
        borough: 'Butte-aux-Cailles',
        category: 'Apartment',
        bedrooms: 1,
        city: 'Paris',
        country: 'France',
        id: 65,
        image: 'https://images.unsplash.com/photo-1565182999561-9c5ed6813233',
        price: 3331,
        rating: 4,
        reviews: 28,
        title: 'Apartment in Canal Saint-Martin with unique charm',
      },
      {
        borough: 'Saint-Germain-des-Pr\u00e9s',
        category: 'Apartment',
        bedrooms: 3,
        city: 'Paris',
        country: 'France',
        id: 66,
        image: 'https://images.unsplash.com/photo-1596424529403-448a0dba59cf',
        price: 4067,
        rating: 4,
        reviews: 22,
        title: 'Apartment in Batignolles with unique charm',
      },
      {
        borough: 'Trocad\u00e9ro',
        category: 'Apartment',
        bedrooms: 4,
        city: 'Paris',
        country: 'France',
        id: 67,
        image: 'https://images.unsplash.com/photo-1596424529403-448a0dba59cf',
        price: 2461,
        rating: 3,
        reviews: 15,
        title: 'Apartment in Gobelins with unique charm',
      },
      {
        borough: 'Trocad\u00e9ro',
        category: 'Apartment',
        bedrooms: 1,
        city: 'Paris',
        country: 'France',
        id: 68,
        image: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae',
        price: 3196,
        rating: 5,
        reviews: 28,
        title: 'Apartment in Le Marais with unique charm',
      },
      {
        borough: 'M\u00e9nilmontant',
        category: 'Apartment',
        bedrooms: 3,
        city: 'Paris',
        country: 'France',
        id: 69,
        image: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae',
        price: 3655,
        rating: 3,
        reviews: 9,
        title: 'Apartment in Gobelins with unique charm',
      },
      {
        borough: 'Butte-aux-Cailles',
        category: 'Studio',
        bedrooms: 3,
        city: 'Paris',
        country: 'France',
        id: 70,
        image: 'https://images.unsplash.com/photo-1605276375032-69b768b550cc',
        price: 2618,
        rating: 5,
        reviews: 6,
        title: 'Apartment in Canal Saint-Martin with unique charm',
      },
      {
        borough: 'Montmartre',
        category: 'Apartment',
        bedrooms: 1,
        city: 'Paris',
        country: 'France',
        id: 71,
        image: 'https://images.unsplash.com/photo-1595152772835-219674b2a8a6',
        price: 4140,
        rating: 4,
        reviews: 30,
        title: 'Apartment in Le Marais with unique charm',
      },
      {
        borough: 'Auteuil',
        category: 'Apartment',
        bedrooms: 2,
        city: 'Paris',
        country: 'France',
        id: 72,
        image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
        price: 1374,
        rating: 4,
        reviews: 13,
        title: 'Apartment in Pigalle with unique charm',
      },
      {
        borough: 'Pigalle',
        category: 'Apartment',
        bedrooms: 1,
        city: 'Paris',
        country: 'France',
        id: 73,
        image: 'https://images.unsplash.com/photo-1596424529403-448a0dba59cf',
        price: 1731,
        rating: 5,
        reviews: 20,
        title: 'Apartment in Les Halles with unique charm',
      },
      {
        borough: 'P\u00e8re Lachaise',
        category: 'Apartment',
        bedrooms: 1,
        city: 'Paris',
        country: 'France',
        id: 74,
        image: 'https://images.unsplash.com/photo-1557683326-6e496f8fac2b',
        price: 3326,
        rating: 5,
        reviews: 5,
        title: 'Apartment in Les Halles with unique charm',
      },
      {
        borough: 'Batignolles',
        category: 'Apartment',
        bedrooms: 2,
        city: 'Paris',
        country: 'France',
        id: 75,
        image: 'https://images.unsplash.com/photo-1605276375032-69b768b550cc',
        price: 2124,
        rating: 4,
        reviews: 11,
        title: 'Apartment in M\u00e9nilmontant with unique charm',
      },
      {
        borough: 'Trocad\u00e9ro',
        category: 'Apartment',
        bedrooms: 4,
        city: 'Paris',
        country: 'France',
        id: 76,
        image: 'https://images.unsplash.com/photo-1595152772835-219674b2a8a6',
        price: 4148,
        rating: 4,
        reviews: 7,
        title: "Apartment in Place d'Italie with unique charm",
      },
      {
        borough: 'Auteuil',
        category: 'Apartment',
        bedrooms: 2,
        city: 'Paris',
        country: 'France',
        id: 77,
        image: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae',
        price: 3179,
        rating: 3,
        reviews: 11,
        title: 'Apartment in Gobelins with unique charm',
      },
      {
        borough: 'Montmartre',
        category: 'Apartment',
        bedrooms: 4,
        city: 'Paris',
        country: 'France',
        id: 78,
        image: 'https://images.unsplash.com/photo-1565182999561-9c5ed6813233',
        price: 2616,
        rating: 3,
        reviews: 21,
        title: "Apartment in Place d'Italie with unique charm",
      },
      {
        borough: 'M\u00e9nilmontant',
        category: 'Apartment',
        bedrooms: 3,
        city: 'Paris',
        country: 'France',
        id: 79,
        image: 'https://images.unsplash.com/photo-1557683326-6e496f8fac2b',
        price: 3743,
        rating: 3,
        reviews: 18,
        title: 'Apartment in Canal Saint-Martin with unique charm',
      },
      {
        borough: 'Champs-\u00c9lys\u00e9es',
        category: 'Apartment',
        bedrooms: 1,
        city: 'Paris',
        country: 'France',
        id: 80,
        image: 'https://images.unsplash.com/photo-1595526110121-b6b5f62e4875',
        price: 2995,
        rating: 4,
        reviews: 28,
        title: 'Apartment in Saint-Germain-des-Pr\u00e9s with unique charm',
      },
      {
        borough: 'M\u00e9nilmontant',
        category: 'Apartment',
        bedrooms: 1,
        city: 'Paris',
        country: 'France',
        id: 81,
        image: 'https://images.unsplash.com/photo-1557683326-6e496f8fac2b',
        price: 2804,
        rating: 3,
        reviews: 26,
        title: 'Apartment in M\u00e9nilmontant with unique charm',
      },
      {
        borough: 'La D\u00e9fense',
        category: 'Apartment',
        bedrooms: 3,
        city: 'Paris',
        country: 'France',
        id: 82,
        image: 'https://images.unsplash.com/photo-1560448204-e2b83c486b95',
        price: 1722,
        rating: 3,
        reviews: 5,
        title: 'Apartment in M\u00e9nilmontant with unique charm',
      },
      {
        borough: 'Le Marais',
        category: 'Apartment',
        bedrooms: 1,
        city: 'Paris',
        country: 'France',
        id: 83,
        image: 'https://images.unsplash.com/photo-1595152772835-219674b2a8a6',
        price: 4713,
        rating: 3,
        reviews: 14,
        title: 'Apartment in Opera with unique charm',
      },
      {
        borough: 'P\u00e8re Lachaise',
        category: 'Apartment',
        bedrooms: 3,
        city: 'Paris',
        country: 'France',
        id: 84,
        image: 'https://images.unsplash.com/photo-1576675788763-d296b2892211',
        price: 4111,
        rating: 5,
        reviews: 12,
        title: 'Apartment in Latin Quarter with unique charm',
      },
      {
        borough: 'Pigalle',
        category: 'Apartment',
        bedrooms: 2,
        city: 'Paris',
        country: 'France',
        id: 85,
        image: 'https://images.unsplash.com/photo-1595526110121-b6b5f62e4875',
        price: 4827,
        rating: 5,
        reviews: 29,
        title: 'Apartment in Auteuil with unique charm',
      },
      {
        borough: 'Auteuil',
        category: 'Apartment',
        bedrooms: 3,
        city: 'Paris',
        country: 'France',
        id: 86,
        image: 'https://images.unsplash.com/photo-1565182999561-9c5ed6813233',
        price: 3884,
        rating: 3,
        reviews: 13,
        title: 'Apartment in Pigalle with unique charm',
      },
      {
        borough: 'Pigalle',
        category: 'Apartment',
        bedrooms: 4,
        city: 'Paris',
        country: 'France',
        id: 87,
        image: 'https://images.unsplash.com/photo-1560448204-e2b83c486b95',
        price: 2426,
        rating: 4,
        reviews: 9,
        title: 'Apartment in Belleville with unique charm',
      },
      {
        borough: 'Opera',
        category: 'Apartment',
        bedrooms: 3,
        city: 'Paris',
        country: 'France',
        id: 88,
        image: 'https://images.unsplash.com/photo-1596424529403-448a0dba59cf',
        price: 3015,
        rating: 3,
        reviews: 5,
        title: 'Apartment in Champs-\u00c9lys\u00e9es with unique charm',
      },
      {
        borough: 'Latin Quarter',
        category: 'Apartment',
        bedrooms: 1,
        city: 'Paris',
        country: 'France',
        id: 89,
        image: 'https://images.unsplash.com/photo-1565182999561-9c5ed6813233',
        price: 4849,
        rating: 5,
        reviews: 8,
        title: 'Apartment in Gobelins with unique charm',
      },
      {
        borough: 'Gobelins',
        category: 'Apartment',
        bedrooms: 3,
        city: 'Paris',
        country: 'France',
        id: 90,
        image: 'https://images.unsplash.com/photo-1576675788763-d296b2892211',
        price: 4134,
        rating: 5,
        reviews: 8,
        title: 'Apartment in Champs-\u00c9lys\u00e9es with unique charm',
      },
      {
        borough: 'Gobelins',
        category: 'Apartment',
        bedrooms: 3,
        city: 'Paris',
        country: 'France',
        id: 91,
        image: 'https://images.unsplash.com/photo-1576675788763-d296b2892211',
        price: 4498,
        rating: 4,
        reviews: 24,
        title: "Apartment in Place d'Italie with unique charm",
      },
      {
        borough: 'Opera',
        category: 'Apartment',
        bedrooms: 2,
        city: 'Paris',
        country: 'France',
        id: 92,
        image: 'https://images.unsplash.com/photo-1605276375032-69b768b550cc',
        price: 1490,
        rating: 5,
        reviews: 23,
        title: 'Apartment in Bastille with unique charm',
      },
      {
        borough: 'Bastille',
        category: 'Apartment',
        bedrooms: 1,
        city: 'Paris',
        country: 'France',
        id: 93,
        image: 'https://images.unsplash.com/photo-1560448204-e2b83c486b95',
        price: 1723,
        rating: 3,
        reviews: 8,
        title: 'Apartment in Gobelins with unique charm',
      },
      {
        borough: 'Trocad\u00e9ro',
        category: 'Apartment',
        bedrooms: 3,
        city: 'Paris',
        country: 'France',
        id: 94,
        image: 'https://images.unsplash.com/photo-1605276375032-69b768b550cc',
        price: 2361,
        rating: 4,
        reviews: 29,
        title: 'Apartment in Les Halles with unique charm',
      },
      {
        borough: 'Canal Saint-Martin',
        category: 'Apartment',
        bedrooms: 3,
        city: 'Paris',
        country: 'France',
        id: 95,
        image: 'https://images.unsplash.com/photo-1595526110121-b6b5f62e4875',
        price: 4759,
        rating: 3,
        reviews: 6,
        title: 'Apartment in Auteuil with unique charm',
      },
      {
        borough: 'Pigalle',
        category: 'Apartment',
        bedrooms: 3,
        city: 'Paris',
        country: 'France',
        id: 96,
        image: 'https://images.unsplash.com/photo-1576675788763-d296b2892211',
        price: 4808,
        rating: 5,
        reviews: 25,
        title: 'Apartment in P\u00e8re Lachaise with unique charm',
      },
      {
        borough: 'Gobelins',
        category: 'Apartment',
        bedrooms: 2,
        city: 'Paris',
        country: 'France',
        id: 97,
        image: 'https://images.unsplash.com/photo-1576675788763-d296b2892211',
        price: 3956,
        rating: 3,
        reviews: 19,
        title: 'Apartment in P\u00e8re Lachaise with unique charm',
      },
      {
        borough: 'Gobelins',
        category: 'Apartment',
        bedrooms: 3,
        city: 'Paris',
        country: 'France',
        id: 98,
        image: 'https://images.unsplash.com/photo-1576675788763-d296b2892211',
        price: 1327,
        rating: 3,
        reviews: 14,
        title: 'Apartment in Bastille with unique charm',
      },
      {
        borough: 'Saint-Germain-des-Pr\u00e9s',
        category: 'Apartment',
        bedrooms: 1,
        city: 'Paris',
        country: 'France',
        id: 99,
        image: 'https://images.unsplash.com/photo-1565182999561-9c5ed6813233',
        price: 2006,
        rating: 4,
        reviews: 7,
        title: 'Apartment in Butte-aux-Cailles with unique charm',
      },
      {
        borough: 'Auteuil',
        category: 'Apartment',
        bedrooms: 3,
        city: 'Paris',
        country: 'France',
        id: 100,
        image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
        price: 2242,
        rating: 3,
        reviews: 26,
        title: 'Apartment in La D\u00e9fense with unique charm',
      },
    ],
    boroughs: [
      'Le Marais',
      'Montmartre',
      'Latin Quarter',
      'Saint-Germain-des-Prés',
      'Belleville',
      'Bastille',
      'Opera',
      'Trocadéro',
      'Canal Saint-Martin',
      'Champs-Élysées',
      'Batignolles',
      'Ménilmontant',
      'Butte-aux-Cailles',
      'La Défense',
      'Pigalle',
      'Père Lachaise',
      'Gobelins',
      "Place d'Italie'",
      'Les Halles',
      'Auteuil',
    ],
    categories: ['Apartment', 'Studio', 'Alcove'],
    accommodation: null,
    savedSearch: [],
  }),
  actions: {
    setAccommodation(accommodation) {
      this.accommodation = accommodation
    },
    filteringAccommodation(form, reset = false) {
      if (reset) return this.accommodations
      let filtered = [...this.accommodations]

      Object.keys(form).forEach((key) => {
        if (form[key] !== null) {
          filtered = filtered.filter((item) => {
            if (key === 'min' || key === 'max') {
              return item.price <= form.min && item.price >= form.max
            } else return item[key] === form[key]
          })
        }
      })

      return filtered
    },
    saveSearch(search) {
      if (!this.savedSearch.find((item) => item !== search)) this.savedSearch.push(search)
    },
    clearSavedSearch(index) {
      this.savedSearch.splice(index, 1)
    },
  },
  persist: ['savedSearch'],
})
